do not build if package already built

diff --git a/mrcommon b/mrcommon
--- a/mrcommon
+++ b/mrcommon
@@ -2,6 +2,84 @@
 # Utility functions to handle arch linux package building and AUR downloads    #
 # ---------------------------------------------------------------------------- #
 
+# Some functions I stole from the pkgbuild script
+lib=
+        have_function() {
+	    declare -f "$1" >/dev/null
+        }
+        ##
+        #  usage : source_safe <pkgbuild>
+        #   desc : source a PKGBUILD safely
+        ##
+        source_safe() {
+            shopt -u extglob
+            if ! source "$@"; then
+                error "$(gettext "Failed to source %s")" "$1"
+                exit 1
+            fi
+            shopt -s extglob
+        }
+        run_function_safe() {
+            local restoretrap
+            local pkgfunc="$1"
+            set -e
+            set -E
+            restoretrap=$(trap -p ERR)
+            trap 'error_function $pkgfunc' ERR
+            $pkgfunc
+            eval $restoretrap
+            set +E
+            set +e
+        }
+        ##
+        #  usage : get_full_version <pkgname>
+        # return : full version spec, including epoch (if necessary), pkgver, pkgrel
+        ##
+        get_full_version() {
+            if [[ -z $1 ]]; then
+                if [[ $epoch ]] && (( ! $epoch )); then
+                    printf "%s\n" "$pkgver-$pkgrel"
+                else
+                    printf "%s\n" "$epoch:$pkgver-$pkgrel"
+                fi
+            else
+                for i in pkgver pkgrel epoch; do
+                    local indirect="${i}_override"
+                    eval $(declare -f package_$1 | sed -n "s/\(^[[:space:]]*$i=\)/${i}_override=/p")
+                    [[ -z ${!indirect} ]] && eval ${indirect}=\"${!i}\"
+                done
+                if (( ! $epoch_override )); then
+                    printf "%s\n" "$pkgver_override-$pkgrel_override"
+                else
+                    printf "%s\n" "$epoch_override:$pkgver_override-$pkgrel_override"
+                fi
+            fi
+        }
+        ##
+        #  usage : get_pkg_arch <pkgname>
+        # return : architecture of the package
+        ##
+        get_pkg_arch() {
+            CARCH=x86_64
+	    if [[ -z $1 ]]; then
+                if [[ $arch = "any" ]]; then
+                    printf "%s\n" "any"
+                else
+                    printf "%s\n" "$CARCH"
+                fi
+            else
+                local arch_override
+                eval $(declare -f package_$1 | sed -n 's/\(^[[:space:]]*arch=\)/arch_override=/p')
+                (( ${#arch_override[@]} == 0 )) && arch_override=("${arch[@]}")
+                if [[ $arch_override = "any" ]]; then
+                    printf "%s\n" "any"
+                else
+                    printf "%s\n" "$CARCH"
+                fi
+            fi
+        }
+
+
 lib=
         builddir="$HOME/opt/arch/build"
         if [ ! -d "$builddir" ]; then
@@ -27,16 +105,37 @@ lib=
                 git commit -m "$message ($num files)"
             fi
         }
-        package_uptodate() {
-            # package_uptodate <path>
-            # Check whether the package is up to date.
-            false
-        }
-        newest_package() {
-            # newest_package <path>
+        built_package_file() {
+            # built_package_file <path>
             # echoes the full path of the newest built package in path
             path="$1"
             find "$path" -maxdepth 1 -name \*.pkg.tar.xz | sort | tail -1            
+        }
+        pkgbuild_package_file() {
+            # pkgbuild_package_file <path>
+            # echoes the full path of the package a build will generate
+            path="$1"
+            pkgbuild="$path/PKGBUILD"
+            ( 
+                cd "$path"
+                source_safe "$pkgbuild"
+                pkgbase=${pkgbase:-${pkgname[0]}}
+                srcdir="$path/src"
+                pkgdir="$path/pkg/$pkgbase"
+                epoch=${epoch:-0}
+                if have_function pkgver; then
+                    pkgver=$(run_function_safe pkgver)
+                fi
+                fullver=$(get_full_version)
+                pkgarch=$(get_pkg_arch)
+                echo "$path/${pkgname}-${fullver}-${pkgarch}.pkg.tar.xz"
+            )         
+        }
+        package_uptodate() {
+            # package_uptodate <path>
+            # Check whether the package is up to date.
+            path="$1"
+            [ "$(built_package_file $path)" == "$(pkgbuild_package_file $path)" ]
         }
         builddir_path() {
             # builddir_path <path>
@@ -73,7 +172,7 @@ lib=
             # Install a package.
             path="$1"
             pkgname=$(basename "$path")
-            pkgfile=$(newest_package "$path")
+            pkgfile=$(built_package_file "$path")
             if [ -f "$pkgfile" ]; then
                 sudo pacman --noconfirm -U "file://$pkgfile"               
             fi             
@@ -84,7 +183,7 @@ lib=
             path="$1"
             tgtrepo="$2"
             pkgname=$(basename "$path")
-            pkgfile=$(newest_package "$path")
+            pkgfile=$(built_package_file "$path")
             repodb=$(basename "$tgtrepo").db.tar.gz
             if [ -f "$pkgfile" ]; then
                 # clean older packages
@@ -117,10 +216,11 @@ lib=
         }
 
 build= 
-         if package_uptodate "$PWD"; then
+         buildpath=$(prepare_build "$PWD")
+         package_download "$buildpath"
+         if package_uptodate "$buildpath"; then
              echo "Package is up to date. No need to rebuild."
          else
-             buildpath=$(prepare_build "$PWD")
              package_build "$buildpath"
          fi
 
